---
language: node_js
node_js:
  - "6.5.0"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

script:
  - ember test --server
